version: '3.8'
services:
  traefik:
    image: traefik:v2.11
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:8888
      - --entrypoints.traefik.address=:8081
    ports:
      - "8888:8888"
      - "8081:8081" # dashboard Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: traefik

  usuarios:
    build: ./app-usuarios
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.usuarios.rule=PathPrefix(/usuarios)"
      - "traefik.http.routers.usuarios.entrypoints=web"
      - "traefik.http.routers.usuarios.middlewares=usuarios-stripprefix"
      - "traefik.http.middlewares.usuarios-stripprefix.stripprefix.prefixes=/usuarios"
      - "traefik.http.services.usuarios.loadbalancer.server.port=8080"
    container_name: usuarios-service
    expose:
      - "8080"

  actividades:
    build: ./app-actividades
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.actividades.rule=PathPrefix(/actividades)"
      - "traefik.http.routers.actividades.entrypoints=web"
      - "traefik.http.routers.actividades.middlewares=actividades-stripprefix"
      - "traefik.http.middlewares.actividades-stripprefix.stripprefix.prefixes=/actividades"
      - "traefik.http.services.actividades.loadbalancer.server.port=8090"
    container_name: actividades-service
    expose:
      - "8090"

# Ahora puedes acceder a:
# http://localhost:8888/usuarios/auth/login -> usuarios (sin /usuarios en la petición interna)
# http://localhost:8888/actividades -> actividades
# Dashboard Traefik: http://localhost:8080