quarkus.hibernate-orm.database.generation=update

quarkus.datasource.db-kind=postgresql
#quarkus.datasource.username=postgres
#quarkus.datasource.password=LAOLl203

#quarkus.datasource.jdbc.driver=org.postgresql.Driver
#quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/tesis

quarkus.datasource.username=tesis_fza8_user
quarkus.datasource.password=CeBiCOvnMFrPOxPrahTt22FtyLpgiBZL
quarkus.datasource.jdbc.url=jdbc:postgresql://dpg-d23bhpbe5dus73afmbjg-a.oregon-postgres.render.com/tesis_fza8

quarkus.http.port=9090

# JWT Configuration (CONSUMER)
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://microservices-auth

# REST Clients
quarkus.rest-client.ReservaRestClient.url=http://localhost:9080
quarkus.rest-client.UsuarioRestClient.url=http://localhost:8080

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*