quarkus.hibernate-orm.database.generation=update

quarkus.datasource.db-kind=postgresql
#quarkus.datasource.username=postgres
#quarkus.datasource.password=LAOLl203

#quarkus.datasource.jdbc.driver=org.postgresql.Driver
#quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/tesis

quarkus.datasource.username=tesis_w46c_user
quarkus.datasource.password=4UpLzEve0tQpissGy5ofsmK12Q4pYLrH
quarkus.datasource.jdbc.url=jdbc:postgresql://dpg-d3h9ss9r0fns73c7ov9g-a.oregon-postgres.render.com/tesis_w46c

quarkus.http.port=9090

# JWT Configuration (CONSUMER)
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://microservices-auth

# REST Clients
quarkus.rest-client.ReservaRestClient.url=http://localhost:9080
quarkus.rest-client.UsuarioRestClient.url=http://localhost:8080

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*  