quarkus.hibernate-orm.database.generation=update

quarkus.datasource.db-kind=postgresql
#quarkus.datasource.username=postgres
#quarkus.datasource.password=LAOLl203

#quarkus.datasource.jdbc.driver=org.postgresql.Driver
#quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/tesis

quarkus.datasource.username=tesis1_sssr
quarkus.datasource.password=0S6MG0ho5H1RoxuvcbvSrC4WqyVZzgho
quarkus.datasource.jdbc.url=jdbc:postgresql://dpg-d4577badbo4c73e95log-a.oregon-postgres.render.com/tesis1_sssr

quarkus.http.port=9090

# JWT Configuration (CONSUMER)
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://microservices-auth

# REST Clients
quarkus.rest-client.ReservaRestClient.url=http://localhost:9080
quarkus.rest-client.UsuarioRestClient.url=http://localhost:8080

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*  

# ============================================
# CONFIGURACIÓN MinIO (DESARROLLO)
# ============================================
aws.s3.bucket-name=turismo-ecuador-bucket
aws.s3.region=us-east-1
aws.s3.access-key=minioadmin
aws.s3.secret-key=minioadmin
aws.s3.endpoint=http://localhost:9000
aws.s3.path-style-access=true

# ============================================
# CONFIGURACIÓN AWS S3 (PRODUCCIÓN)
# Comentar MinIO y descomentar estas líneas
# ============================================
#aws.s3.bucket-name=turismo-ecuador-bucket
#aws.s3.region=us-east-1
#aws.s3.access-key=${AWS_ACCESS_KEY}
#aws.s3.secret-key=${AWS_SECRET_KEY}
#aws.s3.endpoint=
#aws.s3.path-style-access=false

# Tamaño máximo de archivos (10MB)
quarkus.http.body.uploads-directory=/tmp/uploads
quarkus.http.limits.max-body-size=10M