quarkus.hibernate-orm.database.generation=update

quarkus.datasource.db-kind=postgresql
#quarkus.datasource.username=postgres
#quarkus.datasource.password=LAOLl203

#quarkus.datasource.jdbc.driver=org.postgresql.Driver
#quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/tesis

quarkus.datasource.username=tesis_w46c_user
quarkus.datasource.password=4UpLzEve0tQpissGy5ofsmK12Q4pYLrH
quarkus.datasource.jdbc.url=jdbc:postgresql://dpg-d3h9ss9r0fns73c7ov9g-a.oregon-postgres.render.com/tesis_w46c
#postgresql://tesis_w46c_user:4UpLzEve0tQpissGy5ofsmK12Q4pYLrH@dpg-d3h9ss9r0fns73c7ov9g-a.oregon-postgres.render.com/tesis_w46c
quarkus.http.port=8080

# JWT Configuration (ISSUER)
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://microservices-auth
smallrye.jwt.sign.key.location=privateKey.pem

# Token durations
jwt.access-token.duration=PT90M
jwt.refresh-token.duration=P7D

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.headers=*
quarkus.http.cors.methods=*