quarkus.hibernate-orm.database.generation=update

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=LAOLl203

quarkus.datasource.jdbc.driver=org.postgresql.Driver
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/tesis

quarkus.http.port=8080

# JWT Configuration (ISSUER)
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://microservices-auth
smallrye.jwt.sign.key.location=privateKey.pem

# Token durations
jwt.access-token.duration=PT90M
jwt.refresh-token.duration=P7D

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.headers=*
quarkus.http.cors.methods=*