quarkus.hibernate-orm.database.generation=update

quarkus.datasource.db-kind=postgresql
#quarkus.datasource.username=postgres
#quarkus.datasource.password=LAOLl203

#quarkus.datasource.jdbc.driver=org.postgresql.Driver
#quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/tesis

quarkus.datasource.username=tesis_fza8_user
quarkus.datasource.password=CeBiCOvnMFrPOxPrahTt22FtyLpgiBZL
quarkus.datasource.jdbc.url=jdbc:postgresql://dpg-d23bhpbe5dus73afmbjg-a.oregon-postgres.render.com/tesis_fza8

quarkus.http.port=8070

# JWT Configuration (CONSUMER)
mp.jwt.verify.publickey.location=publicKey.pem 
mp.jwt.verify.issuer=https://microservices-auth

# REST Clients
quarkus.rest-client.ActividadRestClient.url=http://localhost:8090
quarkus.rest-client.OpinionRestClient.url=http://localhost:8085
quarkus.rest-client.GaleriaRestClient.url=http://localhost:8090

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*

# Timeouts para REST clients
quarkus.rest-client.ActividadRestClient.connect-timeout=50000
quarkus.rest-client.ActividadRestClient.read-timeout=100000
quarkus.rest-client.OpinionRestClient.connect-timeout=50000
quarkus.rest-client.OpinionRestClient.read-timeout=100000
quarkus.rest-client.GaleriaRestClient.connect-timeout=50000
quarkus.rest-client.GaleriaRestClient.read-timeout=100000
